//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguimientoPermanenciaEntities : DbContext
    {
        public SeguimientoPermanenciaEntities()
            : base("name=SeguimientoPermanenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAutores> tblAutores { get; set; }
        public virtual DbSet<tblCampoBP> tblCampoBP { get; set; }
        public virtual DbSet<tblCEO> tblCEO { get; set; }
        public virtual DbSet<tblImagenBP> tblImagenBP { get; set; }
        public virtual DbSet<tblImagenModuloBanner> tblImagenModuloBanner { get; set; }
        public virtual DbSet<tblModulo> tblModulo { get; set; }
        public virtual DbSet<tblMunicipio> tblMunicipio { get; set; }
        public virtual DbSet<tblPerfil> tblPerfil { get; set; }
        public virtual DbSet<tblPermisoModulo> tblPermisoModulo { get; set; }
        public virtual DbSet<tblPerteneceInsSis> tblPerteneceInsSis { get; set; }
        public virtual DbSet<tblPlantilla> tblPlantilla { get; set; }
        public virtual DbSet<tblFuncionDesarrolloP> tblFuncionDesarrolloP { get; set; }
        public virtual DbSet<tblBuenaPractica> tblBuenaPractica { get; set; }
        public virtual DbSet<tblImagenRevision> tblImagenRevision { get; set; }
        public virtual DbSet<tblRevisionBP> tblRevisionBP { get; set; }
        public virtual DbSet<tblEje> tblEje { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
        public virtual DbSet<tblCampoEvento> tblCampoEvento { get; set; }
        public virtual DbSet<tblEscuelaEvento> tblEscuelaEvento { get; set; }
        public virtual DbSet<tblEvento> tblEvento { get; set; }
        public virtual DbSet<tblFuncionParticipante> tblFuncionParticipante { get; set; }
        public virtual DbSet<tblMesaTrabEvento> tblMesaTrabEvento { get; set; }
        public virtual DbSet<tblMesaTrabParticipante> tblMesaTrabParticipante { get; set; }
        public virtual DbSet<tblMunicipioEvento> tblMunicipioEvento { get; set; }
        public virtual DbSet<tblSubsistemaEvento> tblSubsistemaEvento { get; set; }
        public virtual DbSet<tblRegistroEvento> tblRegistroEvento { get; set; }
        public virtual DbSet<tblTipoRegistro> tblTipoRegistro { get; set; }
        public virtual DbSet<tblUserEnlaceEvento> tblUserEnlaceEvento { get; set; }
    }
}
