//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCampoEvento
    {
        public int idCampoEvento { get; set; }
        public int idEvento { get; set; }
        public bool CCT { get; set; }
        public bool nombrePlantel { get; set; }
        public bool municipio { get; set; }
        public bool regionSEG { get; set; }
        public bool nivel { get; set; }
        public bool instiSubsis { get; set; }
        public bool CURP { get; set; }
        public bool nombre { get; set; }
        public bool apellidoPat { get; set; }
        public bool apellidoMat { get; set; }
        public bool correoElectronico { get; set; }
        public bool telefono { get; set; }
        public bool sexo { get; set; }
        public bool funcion { get; set; }
        public bool mesaTrabajo { get; set; }
    
        public virtual tblEvento tblEvento { get; set; }
    }
}
