//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvento()
        {
            this.tblCampoEvento = new HashSet<tblCampoEvento>();
            this.tblEscuelaEvento = new HashSet<tblEscuelaEvento>();
            this.tblFuncionParticipante = new HashSet<tblFuncionParticipante>();
            this.tblMesaTrabEvento = new HashSet<tblMesaTrabEvento>();
            this.tblMunicipioEvento = new HashSet<tblMunicipioEvento>();
            this.tblSubsistemaEvento = new HashSet<tblSubsistemaEvento>();
            this.tblRegistroEvento = new HashSet<tblRegistroEvento>();
            this.tblUserEnlaceEvento = new HashSet<tblUserEnlaceEvento>();
        }
    
        public int idEvento { get; set; }
        public string nombre { get; set; }
        public string objetivo { get; set; }
        public string rutaIcono { get; set; }
        public System.DateTime fVigenciaInicio { get; set; }
        public System.DateTime fVigenciaFin { get; set; }
        public System.DateTime fRegistroInicio { get; set; }
        public System.DateTime fRegistroFin { get; set; }
        public string rutaPlantillaExcel { get; set; }
        public string tipoEvento { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCampoEvento> tblCampoEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEscuelaEvento> tblEscuelaEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFuncionParticipante> tblFuncionParticipante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesaTrabEvento> tblMesaTrabEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMunicipioEvento> tblMunicipioEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubsistemaEvento> tblSubsistemaEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRegistroEvento> tblRegistroEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserEnlaceEvento> tblUserEnlaceEvento { get; set; }
    }
}
