//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImagenBP
    {
        public int idImagen { get; set; }
        public int buenaPractica { get; set; }
        public int campoBP { get; set; }
        public string imagen { get; set; }
        public string titulo { get; set; }
        public string enumeracion { get; set; }
    
        public virtual tblBuenaPractica tblBuenaPractica { get; set; }
        public virtual tblCampoBP tblCampoBP { get; set; }
    }
}
