//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRevisionBP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRevisionBP()
        {
            this.tblImagenRevision = new HashSet<tblImagenRevision>();
        }
    
        public int idRevision { get; set; }
        public string usuarioRevisor { get; set; }
        public int buenaPractica { get; set; }
        public System.DateTime fechaSoliRevi { get; set; }
        public Nullable<System.DateTime> fechaListaPubli { get; set; }
        public string comentarioTituloBP { get; set; }
        public string comentarioSituacionMejora { get; set; }
        public string comentarioDiagnosticoRealizo { get; set; }
        public string comentarioCaracteristicasContexto { get; set; }
        public string comentarioDescripcionActividadesRealizadas { get; set; }
        public string comentarioElementoInnovador { get; set; }
        public string comentarioResultadosObtenidos { get; set; }
        public string comentarioObservacionesBP { get; set; }
        public string comentarioFuenteInformacion { get; set; }
        public string comentarioGeneral { get; set; }
    
        public virtual tblBuenaPractica tblBuenaPractica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImagenRevision> tblImagenRevision { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
