//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistroEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRegistroEvento()
        {
            this.tblMesaTrabParticipante = new HashSet<tblMesaTrabParticipante>();
        }
    
        public int folio { get; set; }
        public int idEvento { get; set; }
        public string idTipoRegistro { get; set; }
        public string CCT { get; set; }
        public string nombrePlantel { get; set; }
        public string municipio { get; set; }
        public string regionSEG { get; set; }
        public string nivel { get; set; }
        public string instiSubsis { get; set; }
        public string CURP { get; set; }
        public string nombre { get; set; }
        public string apellidoPat { get; set; }
        public string apellidoMat { get; set; }
        public string correoElectronico { get; set; }
        public string telefono { get; set; }
        public string sexo { get; set; }
        public string funcion { get; set; }
    
        public virtual tblEvento tblEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesaTrabParticipante> tblMesaTrabParticipante { get; set; }
        public virtual tblTipoRegistro tblTipoRegistro { get; set; }
    }
}
