//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuario()
        {
            this.tblBuenaPractica = new HashSet<tblBuenaPractica>();
            this.tblPermisoModulo = new HashSet<tblPermisoModulo>();
            this.tblPerteneceInsSis = new HashSet<tblPerteneceInsSis>();
            this.tblRevisionBP = new HashSet<tblRevisionBP>();
            this.tblUserEnlaceEvento = new HashSet<tblUserEnlaceEvento>();
        }
    
        public string nombreUsuario { get; set; }
        public string nombre { get; set; }
        public string pApellido { get; set; }
        public string sApellido { get; set; }
        public string contrasenia { get; set; }
        public string correoElectronico { get; set; }
        public string telefono { get; set; }
        public bool estado { get; set; }
        public int perfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBuenaPractica> tblBuenaPractica { get; set; }
        public virtual tblPerfil tblPerfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermisoModulo> tblPermisoModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerteneceInsSis> tblPerteneceInsSis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRevisionBP> tblRevisionBP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserEnlaceEvento> tblUserEnlaceEvento { get; set; }
    }
}
